"""Score eval-checkpoint answers with a confidence model frozen at one checkpoint.

Unlike :mod:`conset.pred_confidence`, this program always runs the confidence
forward pass with the surrogate checkpoint named in its inference plan. The
adapter can have been trained on one or more separate checkpoints; each
evaluation checkpoint still supplies its own generated answer groups and
judge labels.

For example, this evaluates whether a predictor trained at ``stage1-step424000``
can score answers generated by later checkpoints without exposing the predictor
to those later base-model weights::

    python -m conset.pred_confidence_surrogate \
        --inference_config conset/inference_configs/olmo7b_surrogate.yaml

Prediction artifacts use a separate ``pred_confs_surrogate_*`` namespace and
therefore never overwrite ordinary :mod:`conset.pred_confidence` results.
"""

import argparse
import os

import torch
import yaml

from .pred_confidence import (
    _save_predictions,
    _train_config_path,
    load_eval_examples,
    predict_confidences,
)
from .train_confidence import (
    ConfidenceDataset,
    LeftPadCollator,
    get_adapter_dir,
    get_single_digit_token_ids,
    load_model_and_tokenizer,
    load_train_config,
    set_adapter_root,
)


def run_inference_config(config_path, cli_force=False):
    """Run the surrogate-inference jobs described by a YAML plan.

    The plan has ``models``, ``datasets``, and ``train_configs`` lists.  A
    train-config entry may use ``{dataset}``, which is expanded for every
    dataset entry.  This makes one plan cover the same dataset/config/seed
    Cartesian product that the old shell loop submitted.
    """
    with open(config_path) as f:
        plan = yaml.safe_load(f)
    if not isinstance(plan, dict):
        raise ValueError(f'Inference config {config_path} must contain a mapping')

    models = plan.get('models')
    datasets = plan.get('datasets')
    train_configs = plan.get('train_configs')
    if not isinstance(models, list) or not models:
        raise ValueError("Inference config requires a nonempty 'models' list")
    if not isinstance(datasets, list) or not datasets:
        raise ValueError("Inference config requires a nonempty 'datasets' list")
    if (not isinstance(train_configs, list) or not train_configs
            or not all(isinstance(config, str) and config
                       for config in train_configs)):
        raise ValueError(
            "Inference config requires a nonempty string 'train_configs' list")

    seeds = plan.get('seeds', [17])
    if (not isinstance(seeds, list) or not seeds
            or not all(isinstance(seed, int) for seed in seeds)):
        raise ValueError("'seeds' must be a nonempty list of integers")
    epoch = int(plan.get('epoch', 1))
    batch_size = int(plan.get('batch_size', 32))
    gen_config_name = plan.get('gen_config_name', 'beam')
    is_instruct = plan.get('is_instruct', False)
    if not isinstance(is_instruct, bool):
        raise ValueError("'is_instruct' must be a boolean")
    force = cli_force or bool(plan.get('force', False))

    normalized_datasets = []
    for spec in datasets:
        if not isinstance(spec, dict):
            raise ValueError("Each dataset entry must be a mapping")
        try:
            dataset = spec['dataset']
            beg, end = int(spec['beg']), int(spec['end'])
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(
                'Each dataset entry needs dataset, beg, and end') from exc
        if not isinstance(dataset, str) or not dataset or beg >= end:
            raise ValueError(f'Invalid dataset entry: {spec!r}')
        normalized_datasets.append((dataset, beg, end))

    job_args = []
    for model_spec in models:
        if not isinstance(model_spec, dict):
            raise ValueError('Each model entry must be a mapping')
        try:
            model_name = model_spec['model_name']
            train_revisions = model_spec['train_revisions']
            surrogate_revision = model_spec['surrogate_revision']
            eval_revisions = model_spec['eval_revisions']
        except KeyError as exc:
            raise ValueError(
                'Each model entry needs model_name, train_revisions, '
                'surrogate_revision, and eval_revisions') from exc
        if (not isinstance(model_name, str) or not model_name
                or not isinstance(train_revisions, list) or not train_revisions
                or not all(isinstance(revision, str) and revision
                           for revision in train_revisions)
                or not isinstance(surrogate_revision, str) or not surrogate_revision
                or not isinstance(eval_revisions, list) or not eval_revisions
                or not all(isinstance(revision, str) and revision
                           for revision in eval_revisions)):
            raise ValueError(f'Invalid model entry: {model_spec!r}')
        model_is_instruct = model_spec.get('is_instruct', is_instruct)
        if not isinstance(model_is_instruct, bool):
            raise ValueError("model 'is_instruct' must be a boolean")

        for dataset, beg, end in normalized_datasets:
            for config_template in train_configs:
                train_config = config_template.format(dataset=dataset)
                for seed in seeds:
                    print(
                        f'=== model={model_name}, train_config={train_config}, '
                        f'seed={seed}, dataset={dataset} ===', flush=True)
                    job_args.append(argparse.Namespace(
                        model_name=model_name,
                        train_revisions=train_revisions,
                        surrogate_revision=surrogate_revision,
                        eval_revisions=eval_revisions,
                        train_config=train_config,
                        epoch=epoch,
                        seed=seed,
                        beg=beg,
                        end=end,
                        gen_config_name=gen_config_name,
                        batch_size=batch_size,
                        force=force,
                        dataset=dataset,
                        is_instruct=model_is_instruct,
                    ))
    _run_grouped_lora_jobs(job_args)


def _prepare_lora_job(args):
    """Resolve paths and pending work for one config-mode LoRA job.

    This deliberately does no model loading.  That lets the caller discover
    every pending adapter before loading its shared surrogate checkpoint.
    """
    if args.beg >= args.end:
        raise ValueError(f'invalid range {args.beg}-{args.end}')
    train_config = args.train_config.removesuffix('.yaml')
    cfg = load_train_config(_train_config_path(args.train_config))
    train_ds_label = '+'.join(cfg['dataset'])
    if args.dataset:
        eval_dataset = args.dataset
    elif len(cfg['dataset']) == 1:
        eval_dataset = cfg['dataset'][0]
    else:
        raise ValueError(
            '--dataset is required when the train config has multiple datasets')

    train_revision_key = '_'.join(args.train_revisions)
    adapter_parts = (f'confidence_{train_config}', f'seed{args.seed}',
                     f'epoch{args.epoch}')
    prediction_dir = get_adapter_dir(
        train_ds_label, args.model_name, train_revision_key, *adapter_parts,
        storage='home')
    os.makedirs(prediction_dir, exist_ok=True)
    out_paths = {
        eval_rev: os.path.join(
            prediction_dir,
            f'pred_confs_surrogate_{eval_dataset}_{eval_rev}_'
            f'{args.beg}-{args.end}.pt')
        for eval_rev in args.eval_revisions
    }
    pending_eval_revisions = []
    for eval_rev, out_path in out_paths.items():
        if os.path.exists(out_path) and not args.force:
            print(f'Skipping {eval_rev}: {out_path} exists', flush=True)
        else:
            if os.path.exists(out_path):
                print(f'Overwriting {eval_rev}: {out_path}', flush=True)
            pending_eval_revisions.append(eval_rev)
    if not pending_eval_revisions:
        print('All requested prediction files already exist.', flush=True)
        return None

    adapter_dir = get_adapter_dir(
        train_ds_label, args.model_name, train_revision_key, *adapter_parts,
        storage='read')
    return {
        'args': args,
        'cfg': cfg,
        'train_config': train_config,
        'eval_dataset': eval_dataset,
        'adapter_dir': adapter_dir,
        'out_paths': out_paths,
        'pending_eval_revisions': pending_eval_revisions,
    }


def _run_grouped_lora_jobs(job_args):
    """Run config-mode LoRA jobs, loading each surrogate base model once."""
    from collections import defaultdict
    from peft import PeftModel

    groups = defaultdict(list)
    for args in job_args:
        job = _prepare_lora_job(args)
        if job is not None:
            groups[(args.model_name, args.surrogate_revision)].append(job)
    if not groups:
        print('All requested prediction files already exist.', flush=True)
        return

    for (model_name, surrogate_revision), jobs in groups.items():
        print(f'=== Loading surrogate base model once: {model_name} / '
              f'{surrogate_revision} ({len(jobs)} pending adapter job(s)) ===',
              flush=True)
        model, tokenizer = load_model_and_tokenizer(model_name, surrogate_revision)
        digit_token_ids = get_single_digit_token_ids(tokenizer)
        collator = LeftPadCollator(tokenizer.pad_token_id)
        task_cache = {}
        examples_cache = {}
        try:
            for job in jobs:
                args = job['args']
                print(f'=== adapter training ckpts: {args.train_revisions} ===',
                      flush=True)
                print(f'=== surrogate inference ckpt: {surrogate_revision} ===',
                      flush=True)
                print(f'  Adapter: {job["train_config"]}, seed={args.seed}',
                      flush=True)
                adapter_model = None
                try:
                    adapter_model = PeftModel.from_pretrained(
                        model, job['adapter_dir'])
                    device = next(adapter_model.parameters()).device
                    for eval_rev in job['pending_eval_revisions']:
                        cache_key = (job['eval_dataset'], args.beg, args.end,
                                     eval_rev, args.gen_config_name)
                        if cache_key not in examples_cache:
                            task, examples, n_blacklisted = load_eval_examples(
                                job['eval_dataset'], model_name, eval_rev,
                                args.gen_config_name, args.beg, args.end,
                                task_cache=task_cache)
                            examples_cache[cache_key] = (
                                task, examples, n_blacklisted)
                        task, examples, n_blacklisted = examples_cache[cache_key]
                        print(f'=== answers from eval ckpt: {eval_rev} ===',
                              flush=True)
                        print(f'  {len(examples)} eval instances '
                              f'({n_blacklisted} blacklisted)', flush=True)
                        dataset = ConfidenceDataset(
                            examples, tokenizer, task=task,
                            is_instruct=args.is_instruct)
                        confs = predict_confidences(
                            adapter_model, dataset, collator, digit_token_ids,
                            device, args.batch_size)
                        _save_predictions(
                            examples, confs, args.beg, args.end,
                            job['out_paths'][eval_rev])
                        print(f'  Saved to {job["out_paths"][eval_rev]}',
                              flush=True)
                finally:
                    # Keep the same base instance resident for the next
                    # adapter, rather than reloading the checkpoint per seed.
                    if adapter_model is not None:
                        model = adapter_model.unload()
                        del adapter_model
                        torch.cuda.empty_cache()
        finally:
            del model
            torch.cuda.empty_cache()
    print('\nDone.', flush=True)


def main():
    parser = argparse.ArgumentParser(
        description='Score surrogate confidence from a YAML inference plan')
    parser.add_argument('--inference_config', required=True,
                        help='YAML plan covering multiple surrogate jobs')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite existing prediction files')
    parser.add_argument('--adapter_root', default=os.environ.get('SCRATCH'),
                        help='Root for LoRA adapters; defaults to $SCRATCH')
    args = parser.parse_args()
    set_adapter_root(args.adapter_root)
    run_inference_config(args.inference_config, cli_force=args.force)


if __name__ == '__main__':
    main()
