"""Generate SC-surrogate artifacts consumed by LaTex tables.

For each top answer generated by an evaluation checkpoint, this module finds
every answer group from ``--surrogate_revision`` that is equivalent to that
answer.  Equivalence is exactly the one used by :mod:`conset.gen_cands`:
normalized lexical equality is accepted directly and all other matches require
bidirectional NLI entailment.  The confidence is the total generation
probability of the matching surrogate groups (zero when none match).

Example:
    python -m conset.sc_surrogate \
        --dataset triviaqa \
        --model_name allenai/Olmo-3-1025-7B \
        --surrogate_revision stage1-step424000 \
        --eval_revisions stage1-step566000 stage1-step707000 \
        --eval_ranges 5000-9961
"""

import argparse
import os

import torch

from .dataset_configs import get_dataset_config
from .gen_cands import ENTAIL_I, run_nli
from .train_confidence import load_group_data
from .utils import parse_ranges


def sc_surrogate_prediction_dir(dataset, model_name, surrogate_revision):
    """Directory for SC-surrogate predictions shared across target ckpts."""
    return os.path.join(
        'results', 'conset', dataset, model_name.rsplit('/', 1)[-1],
        'sc_surrogate', surrogate_revision)


def _top_answers(qa_examples, group_strs, group_probs, judge_labels,
                 blacklisted_qis):
    """Return top valid generated answer and label for every local question."""
    tops = [None] * len(qa_examples)
    for qi, groups in enumerate(group_strs):
        if qi in blacklisted_qis or groups is None or not groups:
            continue
        valid = judge_labels[qi, :len(groups)] != -1
        if not valid.any():
            continue
        probs = group_probs[qi, :len(groups)].clone()
        probs[~valid] = -float('inf')
        group_i = probs.argmax().item()
        tops[qi] = (groups[group_i][0], judge_labels[qi, group_i].item())
    return tops


def _candidate_lists(qa_examples, target_tops, surrogate_groups):
    """Build NLI inputs and metadata for target-answer/surrogate-group matches."""
    examples, answer_lists, metadata = [], [], []
    for qi, (qa, top, groups) in enumerate(
            zip(qa_examples, target_tops, surrogate_groups)):
        if top is None or groups is None or not groups:
            continue
        # Keep the target answer at index zero.  The remaining indices identify
        # a surrogate group, even when that group has several sampled strings.
        answers = [top[0]]
        group_for_answer = [None]
        for group_i, group in enumerate(groups):
            for answer in group:
                answers.append(answer)
                group_for_answer.append(group_i)
        if len(answers) <= 1:
            continue
        examples.append(qa)
        answer_lists.append(answers)
        metadata.append((qi, group_for_answer))
    return examples, answer_lists, metadata


def _matching_group_confidences(task, qa_examples, target_tops,
                                surrogate_groups, surrogate_probs):
    """Return one SC-surrogate confidence per local question.

    A newly supplied answer can bridge two pre-existing surrogate groups under
    NLI.  In that rare case both groups are compatible with the target answer,
    so their probability masses are added rather than arbitrarily selecting
    one of them.
    """
    confs = torch.zeros(len(qa_examples), dtype=torch.float32)
    examples, answer_lists, metadata = _candidate_lists(
        qa_examples, target_tops, surrogate_groups)
    if not examples:
        return confs

    # Match gen_cands.py exactly: datasets that do not require the LLM judge
    # use their DatasetConfig's lexical matching rule; the other datasets use
    # the lexical-fast-path plus bidirectional NLI relation in run_nli.
    if not task.needs_llm_judge:
        for (qi, group_for_answer), answers in zip(metadata, answer_lists):
            matching_groups = {
                group_i
                for answer, group_i in zip(answers[1:], group_for_answer[1:])
                if task.answers_match(answers[0], answer)
            }
            if matching_groups:
                confs[qi] = surrogate_probs[qi, list(matching_groups)].sum().float()
        return confs

    print(f'Running lexical/NLI matching for {len(examples)} answers...',
          flush=True)
    nlis = run_nli(task, examples, answer_lists)
    for nli_i, (qi, group_for_answer) in enumerate(metadata):
        matching_groups = set()
        for answer_i, group_i in enumerate(group_for_answer[1:], start=1):
            if (nlis[nli_i, 0, answer_i, ENTAIL_I] >= 0
                    and nlis[nli_i, 0, answer_i].argmax() == ENTAIL_I
                    and nlis[nli_i, answer_i, 0].argmax() == ENTAIL_I):
                matching_groups.add(group_i)
        if matching_groups:
            confs[qi] = surrogate_probs[qi, list(matching_groups)].sum().float()
    return confs


def ensure_sc_surrogate_predictions(dataset, model_name, surrogate_revision,
                                    eval_revisions, ranges,
                                    gen_config_name='beam'):
    """Generate any missing SC-surrogate artifacts and return their directory."""
    if len(ranges) != 1:
        raise ValueError(
            'sc_surrogate.py currently requires exactly one --eval_ranges '
            'segment so its artifacts can use the standard prediction format')
    output_dir = sc_surrogate_prediction_dir(
        dataset, model_name, surrogate_revision)
    range_name = '_'.join(f'{beg}-{end}' for beg, end in ranges)
    expected_paths = [os.path.join(
        output_dir,
        f'pred_confs_sc_surrogate_{dataset}_{revision}_{range_name}.pt')
        for revision in eval_revisions]
    if all(os.path.exists(path) for path in expected_paths):
        return output_dir
    task = get_dataset_config(dataset, ranges=ranges)
    qa_examples = task.load_examples()
    blacklisted_qis = {
        qi for qi, absolute_qi in enumerate(
            index for beg, end in ranges for index in range(beg, end))
        if absolute_qi in task.get_blacklist()
    }
    os.makedirs(output_dir, exist_ok=True)

    print(f'Loading surrogate groups: {surrogate_revision}', flush=True)
    _, surrogate_groups, surrogate_probs, _ = load_group_data(
        dataset, model_name, surrogate_revision, gen_config_name, ranges,
        qa_examples=qa_examples)
    for eval_revision in eval_revisions:
        output_path = os.path.join(
            output_dir,
            f'pred_confs_sc_surrogate_{dataset}_{eval_revision}_{range_name}.pt')
        if os.path.exists(output_path):
            print(f'Already exists, skipping: {output_path}', flush=True)
            continue

        print(f'Loading target top answers: {eval_revision}', flush=True)
        _, groups, probs, labels = load_group_data(
            dataset, model_name, eval_revision, gen_config_name, ranges,
            qa_examples=qa_examples)
        target_tops = _top_answers(
            qa_examples, groups, probs, labels, blacklisted_qis)
        confs = _matching_group_confidences(
            task, qa_examples, target_tops, surrogate_groups, surrogate_probs)

        saved_confs = torch.full((len(qa_examples),), float('nan'))
        saved_labels = torch.full((len(qa_examples),), -1, dtype=torch.long)
        for qi, top in enumerate(target_tops):
            if top is not None:
                saved_confs[qi] = confs[qi]
                saved_labels[qi] = top[1]
        torch.save({
            'confs': saved_confs,
            'judge_labels': saved_labels,
            'dataset': dataset,
            'model_name': model_name,
            'surrogate_revision': surrogate_revision,
            'eval_revision': eval_revision,
            'eval_ranges': ranges,
        }, output_path)
        print(f'Saved {output_path}', flush=True)
    return output_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dataset', required=True)
    parser.add_argument('--model_name', required=True)
    parser.add_argument('--surrogate_revision', required=True)
    parser.add_argument('--eval_revisions', nargs='+', required=True)
    parser.add_argument('--eval_ranges', nargs='+', required=True)
    args = parser.parse_args()
    ensure_sc_surrogate_predictions(
        args.dataset, args.model_name, args.surrogate_revision,
        args.eval_revisions, parse_ranges(args.eval_ranges))


if __name__ == '__main__':
    main()
